### ISSUE TITLE
Práctica

### ISSUE THREAD

**Issue by AricelCastro** [SistemasTecTlaxiaco/actividad-3-practica-architect-AricelCastro#1]
[practicaaricel.pdf](https://github.com/user-attachments/files/16841852/practicaaricel.pdf)

**Comment by RodolfoNV** [comment]
Recibo de enterado. En base a la rubrica hace falta imágenes. 
Calificación 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
